### ISSUE TITLE
Incorrect distance calculation / can't express box in Western Hemisphere? 

### ISSUE THREAD

**Issue by Quafadas** [plokhotnyuk/rtree2d#262]
```
val innerBox: RTreeEntry[String] = entry[String](17.84f, -67.38f, 18.62f, -65.51f, "innerBox")

innerBox.asJson.toString()

val h_latitude = 18.0f
val h_longditude = -74.3f

SphericalEarth.distanceCalculator.distance(h_latitude, h_longditude, innerBox)
```
This produces an answer of zero, which I think is "wrong" (or at least, not what I want)

what I think is happening, is that the -ve longitude constraint is going "the wrong way" around the world. However, I can't switch the numbers around, because the library complains at me. 

Any hint on how this might work?

**Comment by plokhotnyuk** [comment]
@Quafadas Thank you for the reporting! Please peek the v0.11.7 release with a fix: https://github.com/plokhotnyuk/rtree2d/releases/tag/v0.11.7

**Comment by Quafadas** [comment]
Works great - thanks!
